package com.gcm.md.models.jsongen;

import uk.co.real_logic.sbe.ir.Ir;
import uk.co.real_logic.sbe.ir.Token;
import uk.co.real_logic.sbe.xml.IrGenerator;
import uk.co.real_logic.sbe.xml.MessageSchema;
import uk.co.real_logic.sbe.xml.ParserOptions;
import uk.co.real_logic.sbe.xml.XmlSchemaParser;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Entry point invoked by the gcm-md-models-json module at generate-sources time.
 *
 * args[0] = path to gcm-md-sbe.xml
 * args[1] = output dir for generated Java sources (translators + registry)
 * args[2] = output dir for generated resources (schemas/, asyncapi/)
 * args[3] = package for generated translators (e.g. com.gcm.md.models.json.translators)
 *
 * The runtime support package (JsonTranslator, JsonWriter) is derived as the parent
 * package of the translator package.
 */
public final class JsonGenMain
{
    public static void main(final String[] args) throws Exception
    {
        if (args.length != 4)
        {
            System.err.println(
                "usage: JsonGenMain <schema.xml> <javaOutDir> <resourcesOutDir> <translatorPackage>");
            System.exit(2);
        }

        final Path schemaXml = Path.of(args[0]);
        final Path javaOut = Path.of(args[1]);
        final Path resourcesOut = Path.of(args[2]);
        final String translatorPackage = args[3];
        final String runtimePackage = translatorPackage.substring(0, translatorPackage.lastIndexOf('.'));

        final MessageSchema schema;
        try (InputStream in = Files.newInputStream(schemaXml))
        {
            final ParserOptions options = ParserOptions.builder().stopOnError(true).build();
            schema = XmlSchemaParser.parse(in, options);
        }

        final Ir ir = new IrGenerator().generate(schema);
        final String sbePackage = ir.packageName();

        final List<Model.Message> messages = new ArrayList<>();
        for (final List<Token> messageTokens : ir.messages())
        {
            messages.add(IrWalker.walk(messageTokens));
        }

        // --- Java: translators + registry -------------------------------------------------
        final Path pkgDir = javaOut.resolve(translatorPackage.replace('.', '/'));
        Files.createDirectories(pkgDir);

        final TranslatorEmitter translatorEmitter = new TranslatorEmitter();
        for (final Model.Message m : messages)
        {
            final String source = translatorEmitter.emit(m, sbePackage, translatorPackage, runtimePackage);
            write(pkgDir.resolve(TranslatorEmitter.className(m.name) + ".java"), source);
        }
        write(pkgDir.resolve("GcmMdTranslators.java"),
            registrySource(messages, translatorPackage, runtimePackage));

        // --- Resources: JSON Schemas + AsyncAPI --------------------------------------------
        final Path schemasDir = resourcesOut.resolve("schemas");
        Files.createDirectories(schemasDir);
        for (final Model.Message m : messages)
        {
            write(schemasDir.resolve(m.name + ".schema.json"), JsonSchemaEmitter.emit(m));
        }

        final Path asyncApiDir = resourcesOut.resolve("asyncapi");
        Files.createDirectories(asyncApiDir);
        write(asyncApiDir.resolve("asyncapi.yaml"), AsyncApiEmitter.emit(messages, ir.id(), ir.version()));

        System.out.println("[gcm-md-models-json-gen] generated " + messages.size() +
            " translator(s), " + messages.size() + " schema(s) and asyncapi.yaml from " + schemaXml);
    }

    private static String registrySource(final List<Model.Message> messages,
                                         final String translatorPackage, final String runtimePackage)
    {
        final StringBuilder b = new StringBuilder(1024);
        b.append("// Generated by gcm-md-models-json-gen. DO NOT EDIT.\n");
        b.append("package ").append(translatorPackage).append(";\n\n");
        b.append("import org.agrona.collections.Int2ObjectHashMap;\n");
        b.append("import ").append(runtimePackage).append(".JsonTranslator;\n\n");
        b.append("/**\n");
        b.append(" * Registry of all generated translators keyed by SBE templateId.\n");
        b.append(" * Translator instances are NOT thread-safe: call create() once per thread\n");
        b.append(" * (e.g. once per NATS dispatcher) and confine the returned map to that thread.\n");
        b.append(" */\n");
        b.append("public final class GcmMdTranslators\n");
        b.append("{\n");
        b.append("    private GcmMdTranslators()\n");
        b.append("    {\n");
        b.append("    }\n\n");
        b.append("    public static Int2ObjectHashMap<JsonTranslator> create()\n");
        b.append("    {\n");
        b.append("        final Int2ObjectHashMap<JsonTranslator> map = new Int2ObjectHashMap<>();\n");
        int i = 0;
        for (final Model.Message m : messages)
        {
            final String var = "t" + i++;
            b.append("        final JsonTranslator ").append(var).append(" = new ")
                .append(TranslatorEmitter.className(m.name)).append("();\n");
            b.append("        map.put(").append(var).append(".templateId(), ").append(var).append(");\n");
        }
        b.append("        return map;\n");
        b.append("    }\n");
        b.append("}\n");
        return b.toString();
    }

    private static void write(final Path path, final String content) throws Exception
    {
        Files.write(path, content.getBytes(StandardCharsets.UTF_8));
    }
}
