package com.gcm.md.models.jsongen;

import uk.co.real_logic.sbe.PrimitiveType;

import java.util.List;

import static com.gcm.md.models.jsongen.IrWalker.upperFirst;

/**
 * Emits one hand-rolled-style translator class per message. Each translator wraps the
 * generated SBE decoder flyweight and writes JSON bytes directly into a MutableDirectBuffer
 * via JsonWriter - no intermediate POJOs, no reflection, no per-message allocation
 * (except JDK-internal allocation in the generated String accessors for char arrays
 * and var-length strings, and Double.toString for floating point).
 *
 * Field access order follows the IR (fixed fields, then groups, then var data), which is
 * the mandatory SBE decode order.
 */
final class TranslatorEmitter
{
    private int varCounter;

    static String className(final String messageName)
    {
        return upperFirst(messageName) + "JsonTranslator";
    }

    String emit(final Model.Message m, final String sbePackage, final String translatorPackage, final String runtimePackage)
    {
        varCounter = 0;
        final String decoderClass = upperFirst(m.name) + "Decoder";
        final StringBuilder b = new StringBuilder(4096);

        b.append("// Generated by gcm-md-models-json-gen. DO NOT EDIT.\n");
        b.append("package ").append(translatorPackage).append(";\n\n");
        b.append("import org.agrona.DirectBuffer;\n");
        b.append("import org.agrona.MutableDirectBuffer;\n");
        b.append("import ").append(runtimePackage).append(".JsonTranslator;\n");
        b.append("import ").append(runtimePackage).append(".JsonWriter;\n");
        b.append("import ").append(sbePackage).append(".*;\n\n");
        b.append("public final class ").append(className(m.name)).append(" implements JsonTranslator\n");
        b.append("{\n");
        b.append("    private final ").append(decoderClass).append(" dec = new ").append(decoderClass).append("();\n");
        b.append("    private final JsonWriter w = new JsonWriter();\n\n");
        b.append("    @Override\n");
        b.append("    public int templateId()\n");
        b.append("    {\n");
        b.append("        return ").append(decoderClass).append(".TEMPLATE_ID;\n");
        b.append("    }\n\n");
        b.append("    @Override\n");
        b.append("    public String messageName()\n");
        b.append("    {\n");
        b.append("        return \"").append(m.name).append("\";\n");
        b.append("    }\n\n");
        b.append("    @Override\n");
        b.append("    public int translate(\n");
        b.append("        final DirectBuffer buffer,\n");
        b.append("        final int offset,\n");
        b.append("        final int actingBlockLength,\n");
        b.append("        final int actingVersion,\n");
        b.append("        final MutableDirectBuffer out)\n");
        b.append("    {\n");
        b.append("        dec.wrap(buffer, offset, actingBlockLength, actingVersion);\n");
        b.append("        w.wrap(out);\n");
        b.append("        w.beginObject();\n");
        emitProps(b, "        ", "dec", decoderClass, m.props);
        b.append("        w.endObject();\n");
        b.append("        return w.length();\n");
        b.append("    }\n");
        b.append("}\n");
        return b.toString();
    }

    private void emitProps(final StringBuilder b, final String ind, final String expr,
                           final String ownerDecoderClass, final List<Model.Prop> props)
    {
        for (final Model.Prop p : props)
        {
            if (p instanceof Model.PrimitiveProp)
            {
                emitPrimitive(b, ind, expr, ownerDecoderClass, (Model.PrimitiveProp)p);
            }
            else if (p instanceof Model.EnumProp)
            {
                emitEnum(b, ind, expr, (Model.EnumProp)p);
            }
            else if (p instanceof Model.SetProp)
            {
                emitSet(b, ind, expr, (Model.SetProp)p);
            }
            else if (p instanceof Model.CompositeProp)
            {
                emitComposite(b, ind, expr, (Model.CompositeProp)p);
            }
            else if (p instanceof Model.GroupProp)
            {
                emitGroup(b, ind, expr, ownerDecoderClass, (Model.GroupProp)p);
            }
            else if (p instanceof Model.VarDataProp)
            {
                emitVarData(b, ind, expr, (Model.VarDataProp)p);
            }
        }
    }

    private void emitPrimitive(final StringBuilder b, final String ind, final String expr,
                               final String ownerDecoderClass, final Model.PrimitiveProp p)
    {
        if (p.isCharArray())
        {
            // sbe-tool generates a String accessor for char arrays with a character encoding
            b.append(ind).append("w.name(\"").append(p.name).append("\"); w.valueFixedString(")
                .append(expr).append('.').append(p.name).append("());\n");
            return;
        }

        if (p.arrayLength > 1)
        {
            final String i = nextVar();
            b.append(ind).append("w.name(\"").append(p.name).append("\");\n");
            b.append(ind).append("w.beginArray();\n");
            b.append(ind).append("for (int ").append(i).append(" = 0; ").append(i).append(" < ")
                .append(p.arrayLength).append("; ").append(i).append("++)\n");
            b.append(ind).append("{\n");
            b.append(ind).append("    w.").append(valueCall(p)).append('(')
                .append(expr).append('.').append(p.name).append('(').append(i).append("));\n");
            b.append(ind).append("}\n");
            b.append(ind).append("w.endArray();\n");
            return;
        }

        if (p.optional)
        {
            final String v = nextVar();
            b.append(ind).append("{\n");
            b.append(ind).append("    final ").append(javaType(p.type)).append(' ').append(v)
                .append(" = ").append(expr).append('.').append(p.name).append("();\n");
            final String condition;
            if (p.type == PrimitiveType.FLOAT)
            {
                condition = "!Float.isNaN(" + v + ")";
            }
            else if (p.type == PrimitiveType.DOUBLE)
            {
                condition = "!Double.isNaN(" + v + ")";
            }
            else
            {
                condition = v + " != " + ownerDecoderClass + "." + p.name + "NullValue()";
            }
            b.append(ind).append("    if (").append(condition).append(")\n");
            b.append(ind).append("    {\n");
            b.append(ind).append("        w.name(\"").append(p.name).append("\"); w.")
                .append(valueCall(p)).append('(').append(v).append(");\n");
            b.append(ind).append("    }\n");
            b.append(ind).append("}\n");
            return;
        }

        b.append(ind).append("w.name(\"").append(p.name).append("\"); w.").append(valueCall(p))
            .append('(').append(expr).append('.').append(p.name).append("());\n");
    }

    private void emitEnum(final StringBuilder b, final String ind, final String expr, final Model.EnumProp p)
    {
        final String enumClass = upperFirst(p.typeName);
        final String v = nextVar();
        b.append(ind).append("{\n");
        b.append(ind).append("    final ").append(enumClass).append(' ').append(v)
            .append(" = ").append(expr).append('.').append(p.name).append("();\n");
        b.append(ind).append("    if (").append(v).append(" != ").append(enumClass).append(".NULL_VAL)\n");
        b.append(ind).append("    {\n");
        b.append(ind).append("        w.name(\"").append(p.name).append("\"); w.valueString(")
            .append(v).append(".name());\n");
        b.append(ind).append("    }\n");
        b.append(ind).append("}\n");
    }

    private void emitSet(final StringBuilder b, final String ind, final String expr, final Model.SetProp p)
    {
        final String setClass = upperFirst(p.typeName) + "Decoder";
        final String v = nextVar();
        b.append(ind).append("w.name(\"").append(p.name).append("\");\n");
        b.append(ind).append("{\n");
        b.append(ind).append("    final ").append(setClass).append(' ').append(v)
            .append(" = ").append(expr).append('.').append(p.name).append("();\n");
        b.append(ind).append("    w.beginArray();\n");
        for (final String choice : p.choices)
        {
            b.append(ind).append("    if (").append(v).append('.').append(choice).append("())\n");
            b.append(ind).append("    {\n");
            b.append(ind).append("        w.valueString(\"").append(choice).append("\");\n");
            b.append(ind).append("    }\n");
        }
        b.append(ind).append("    w.endArray();\n");
        b.append(ind).append("}\n");
    }

    private void emitComposite(final StringBuilder b, final String ind, final String expr, final Model.CompositeProp p)
    {
        final String compClass = upperFirst(p.typeName) + "Decoder";
        final String v = nextVar();
        b.append(ind).append("w.name(\"").append(p.name).append("\");\n");
        b.append(ind).append("{\n");
        b.append(ind).append("    final ").append(compClass).append(' ').append(v)
            .append(" = ").append(expr).append('.').append(p.name).append("();\n");
        b.append(ind).append("    w.beginObject();\n");
        emitProps(b, ind + "    ", v, compClass, p.parts);
        b.append(ind).append("    w.endObject();\n");
        b.append(ind).append("}\n");
    }

    private void emitGroup(final StringBuilder b, final String ind, final String expr,
                           final String ownerDecoderClass, final Model.GroupProp p)
    {
        // Group decoders are inner classes of their enclosing decoder class.
        final String groupClass = ownerDecoderClass + "." + upperFirst(p.name) + "Decoder";
        final String v = nextVar();
        b.append(ind).append("w.name(\"").append(p.name).append("\");\n");
        b.append(ind).append("w.beginArray();\n");
        b.append(ind).append("for (final ").append(groupClass).append(' ').append(v)
            .append(" : ").append(expr).append('.').append(p.name).append("())\n");
        b.append(ind).append("{\n");
        b.append(ind).append("    w.beginObject();\n");
        emitProps(b, ind + "    ", v, groupClass, p.members);
        b.append(ind).append("    w.endObject();\n");
        b.append(ind).append("}\n");
        b.append(ind).append("w.endArray();\n");
    }

    private void emitVarData(final StringBuilder b, final String ind, final String expr, final Model.VarDataProp p)
    {
        if (!p.isString())
        {
            b.append(ind).append("// binary varData field '").append(p.name).append("' skipped (no JSON mapping)\n");
            b.append(ind).append(expr).append('.').append("skip").append(upperFirst(p.name)).append("();\n");
            return;
        }
        b.append(ind).append("w.name(\"").append(p.name).append("\"); w.valueString(")
            .append(expr).append('.').append(p.name).append("());\n");
    }

    private static String valueCall(final Model.PrimitiveProp p)
    {
        switch (p.type)
        {
            case INT64:
                return "valueLongAsString";
            case UINT64:
                return "valueULongAsString";
            case FLOAT:
            case DOUBLE:
                return "valueDouble";
            case CHAR:
                return "valueCharAscii";
            default:
                return "valueLong";
        }
    }

    private static String javaType(final PrimitiveType type)
    {
        switch (type)
        {
            case CHAR:
            case INT8:
                return "byte";
            case INT16:
                return "short";
            case INT32:
                return "int";
            case INT64:
            case UINT32:
            case UINT64:
                return "long";
            case UINT8:
                return "short";
            case UINT16:
                return "int";
            case FLOAT:
                return "float";
            case DOUBLE:
                return "double";
            default:
                throw new IllegalStateException("Unhandled primitive type: " + type);
        }
    }

    private String nextVar()
    {
        return "v" + varCounter++;
    }
}
