{{- if .Values.lineHandlerTemplate.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gcm-md.lineHandlerTemplate.name" . }}-config
  labels:
    {{- include "gcm-md.labels" . | nindent 4 }}
    app.kubernetes.io/component: line-handler-template
data:
  application.yml: |
{{ .Values.lineHandlerTemplate.configYaml | indent 4 }}
{{- end }}
