{{- if .Values.lineHandlerTemplate.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gcm-md.lineHandlerTemplate.name" . }}
  labels:
    {{- include "gcm-md.labels" . | nindent 4 }}
    app.kubernetes.io/component: line-handler-template
{{- end }}
