{{- if .Values.natsBridge.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcm-md.natsBridge.name" . }}
  labels:
    {{- include "gcm-md.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats-bridge
spec:
  selector:
    app.kubernetes.io/component: nats-bridge
  ports:
    - name: http
      port: {{ .Values.natsBridge.serverPort }}
      targetPort: http
{{- end }}
