{{- if .Values.mockUpstreamSource.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcm-md.mockUpstreamSource.name" . }}
  labels:
    {{- include "gcm-md.labels" . | nindent 4 }}
    app.kubernetes.io/component: mock-upstream-source
spec:
  selector:
    app.kubernetes.io/component: mock-upstream-source
  ports:
    - name: http
      port: {{ .Values.mockUpstreamSource.serverPort }}
      targetPort: http
{{- end }}
