{{- if .Values.mockUpstreamSource.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gcm-md.mockUpstreamSource.name" . }}
  labels:
    {{- include "gcm-md.labels" . | nindent 4 }}
    app.kubernetes.io/component: mock-upstream-source
{{- end }}
